# -*- coding: utf-8 -*-
"""fakenewsdetectiondl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVk9eGgBeq5CLUfjwJQoNKdWmGMQjRyM
"""

!pip install -q pandas numpy scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Libraries imported successfully!")

uploaded = files.upload()

print("\nUploaded files:")
for filename in uploaded.keys():
    print(filename)

import os

print("Files in Colab:")
print(os.listdir("/content"))

train_df = pd.read_csv("/content/training.csv")
test_df = pd.read_csv("/content/test.csv")
validation_df = pd.read_csv("/content/validation.csv")

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)
print("Validation shape:", validation_df.shape)

print("TRAIN COLUMNS:")
print(train_df.columns.tolist())

print("\nTEST COLUMNS:")
print(test_df.columns.tolist())

print("\nVALIDATION COLUMNS:")
print(validation_df.columns.tolist())

print("\nFirst 5 rows of training data:")
display(train_df.head())

print("Available columns:", train_df.columns.tolist())

# Possible names for text column
text_candidates = [
    "text", "Text", "sentence", "Sentence",
    "content", "Content", "utterance", "Utterance"
]

# Possible names for emotion/label column
label_candidates = [
    "emotion", "Emotion", "label", "Label",
    "sentiment", "Sentiment", "category", "Category"
]

TEXT_COLUMN = None
LABEL_COLUMN = None

for col in text_candidates:
    if col in train_df.columns:
        TEXT_COLUMN = col
        break

for col in label_candidates:
    if col in train_df.columns:
        LABEL_COLUMN = col
        break

print("Detected text column:", TEXT_COLUMN)
print("Detected emotion column:", LABEL_COLUMN)

train_df = train_df[['text', 'label']].copy()
test_df = test_df[['text', 'label']].copy()
validation_df = validation_df[['text', 'label']].copy()

# Remove missing values
train_df.dropna(inplace=True)
test_df.dropna(inplace=True)
validation_df.dropna(inplace=True)

# Convert to string
train_df['text'] = train_df['text'].astype(str)
test_df['text'] = test_df['text'].astype(str)
validation_df['text'] = validation_df['text'].astype(str)

train_df['label'] = train_df['label'].astype(str)
test_df['label'] = test_df['label'].astype(str)

validation_df['label'] = validation_df['label'].astype(str)

print("Training samples:", len(train_df))
print("Testing samples:", len(test_df))
print("Validation samples:", len(validation_df))

print("Emotion labels:")

for emotion in sorted(train_df['label'].unique()):
    print(emotion)

print("\nTotal number of emotions:",
      train_df['label'].nunique())

display(train_df.head(10))

X_train = train_df['text']
y_train = train_df['label']

X_test = test_df['text']
y_test = test_df['label']

X_validation = validation_df['text']
y_validation = validation_df['label']

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

print("X_validation:", X_validation.shape)
print("y_validation:", y_validation.shape)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=10000,
    stop_words='english',
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

X_validation_tfidf = tfidf.transform(X_validation)

print("TF-IDF conversion completed!")

print("Training shape:", X_train_tfidf.shape)
print("Testing shape:", X_test_tfidf.shape)
print("Validation shape:", X_validation_tfidf.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000
)

model.fit(X_train_tfidf, y_train)

print("Emotion Recognition Model trained successfully!")

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", round(accuracy * 100, 2), "%")

y_val_pred = model.predict(X_validation_tfidf)

validation_accuracy = accuracy_score(
    y_validation,
    y_val_pred
)

print("Validation Accuracy:",
      round(validation_accuracy * 100, 2), "%")

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred,
    zero_division=0
))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

labels = sorted(train_df['label'].unique())

cm = confusion_matrix(
    y_test,
    y_pred,
    labels=labels
)

plt.figure(figsize=(10, 7))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    xticklabels=labels,
    yticklabels=labels
)

plt.xlabel("Predicted Emotion")
plt.ylabel("Actual Emotion")
plt.title("Emotion Recognition Confusion Matrix")

plt.show()

def predict_emotion(text):
    text_tfidf = tfidf.transform([text])
    prediction = model.predict(text_tfidf)[0]

    return prediction

text = input("Enter a sentence: ")

emotion = predict_emotion(text)

print("\nPredicted Emotion:", emotion)

def predict_emotion_with_confidence(text):

    text_tfidf = tfidf.transform([text])

    probabilities = model.predict_proba(text_tfidf)[0]

    index = np.argmax(probabilities)

    emotion = model.classes_[index]

    confidence = probabilities[index] * 100

    return emotion, confidence

text = input("Enter a sentence: ")

emotion, confidence = predict_emotion_with_confidence(text)

print("\n==============================")
print("   EMOTION RECOGNITION")
print("==============================")
print("Input Text:", text)
print("Predicted Emotion:", emotion)
print("Confidence:", round(confidence, 2), "%")

sentences = [
    "I am extremely happy today",
    "I am very angry with him",
    "I am scared about what will happen",
    "I feel lonely and sad",
    "I love spending time with my family",
    "Wow, I did not expect this"
]

for sentence in sentences:

    emotion, confidence = predict_emotion_with_confidence(sentence)

    print("--------------------------------")
    print("Text:", sentence)
    print("Emotion:", emotion)
    print("Confidence:", round(confidence, 2), "%")